## Numpy and Pandas major syntaxes walkthrough

### Agenda:

**Numpy:**
1. Numpy overview
2. Array creation (ex., np.ones(),linspace,arange)
3. Array manipulation-binary operations, matrix multiplication
4. Array iteration
5. Indexing, slicing, reshaping
6. Searching, Sorting
7. Statistical functions
8. np.nan

**Pandas:**
1. loc,iloc, sorting by a column
2. Missing values functions - fillna,isnull(),dropna
3. Slicing with multiple conditions
4. Performing binary operations with the columns of the data frame
5. Typecasting a series of the dataframe - astype(),to_numeric()
6. A brief idea on statistical functions- mean, median, mode with describe function
7. comparing two series/array-like objects using .all() any()
8. descriptive stats- row or column-wise function application
9. nlargest()/ nsmallest()

## <u>Numpy</u>

Using NumPy, a developer can perform the following operations −

Mathematical and logical operations on arrays.
Fourier transforms and routines for shape manipulation.
Operations related to linear algebra. NumPy has in-built functions for linear algebra and random number generation.
NumPy – A Replacement for MatLab

NumPy is often used along with packages like SciPy (Scientific Python) and Matplotlib (plotting library). This combination is widely used as a replacement for MatLab, a popular platform for technical computing. However, Python alternative to MatLab is now seen as a more modern and complete programming language.

It is open-source, which is an added advantage of NumPy.

In [ ]:
list1 = ['Sam', 21, 34.4, 'First class']

### Array creation

In [25]:
import numpy as np 

# creating one-dimensional array
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [32]:
# more than one dimensions
arr = np.array([[1,2,3], [4,5,6]])
arr.shape

(2, 3)

In [39]:
# minimum dimensions
a = np.array([1, 2, 3,4,5], ndmin = 2) 
print(a)

[[1 2 3 4 5]]


In [35]:
a.ndim

1

In [30]:
# np zeroes
arr = np.zeros((2,3))
print(arr)

# np ones
arr = np.ones((2,2))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]


In [42]:
# np.arange()
np.arange(1, 15, 2)

array([ 1,  3,  5,  7,  9, 11, 13])

In [43]:
# using array-scalar type
dt = np.dtype(np.int32) 
print(dt)

int32


In [45]:
#int8, int16, int32, int64 can be replaced by equivalent string 'i1', 'i2','i4', etc.
dt = np.dtype('i4')
print(dt)

int32


In [ ]:
# using endian notation
dt = np.dtype('>i4') 
print(dt)

In [ ]:
# first create structured data type 
import numpy as np 
dt = np.dtype([('age',np.int8)]) 
print(dt)

In [44]:
# now apply it to ndarray object 
dt = np.dtype([('age',np.int8)]) 
a = np.array([(10,),(20,),(30,)], dtype = dt) 
print(a)

[(10,) (20,) (30,)]


In [53]:
# random.randint
np.random.randint(3, 5, size=(3,3))

array([[3, 4, 4],
       [4, 3, 3],
       [3, 4, 3]])

### linspace

NUMPY LINSPACE CREATES SEQUENCES OF EVENLY SPACED VALUES WITHIN AN INTERVAL

In [60]:
# linspace
np.linspace(1, 100, num=6, dtype=np.int32)

array([  1,  20,  40,  60,  80, 100], dtype=int32)

### ndarray.shape

In [68]:
# np.array.shape
arr = np.array([[3,4,5], [1,2,3]])
print(arr)
arr.shape

[[3 4 5]
 [1 2 3]]


(2, 3)

In [69]:
arr = np.array([[[3,4,5]], [[1,2,3]]])
print(arr)
arr.shape

[[[3 4 5]]

 [[1 2 3]]]


(2, 1, 3)

In [77]:
# this resizes the ndarray
a = np.array([[1,2,3],[4,5,6]])
print(a)
a.resize(3,2)
a

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

### ndarray.ndim

In [ ]:
# an array of evenly spaced numbers
a = np.arange(24) 
print(a)

In [82]:
# this is one dimensional array
a = np.arange(24) 
print(a)
print(a.ndim)  

# now reshape it 
b = a.reshape(2,2,6) 
print(b) 

# b is having three dimensions

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1
[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]
  [18 19 20 21 22 23]]]


### numpy.itemsize

In [83]:
# dtype of array is int8 (1 byte)
x = np.array([1,2,3,4,5], dtype = np.int8)
print(x.itemsize)

1


In [84]:
# dtype of array is now float32 (4 bytes) 
import numpy as np 
x = np.array([1,2,3,4,5], dtype = np.float32) 
print(x)
print(x.itemsize)

[1. 2. 3. 4. 5.]
4


### NumPy – Array Creation Routines

In [93]:
x = np.empty([2,3], dtype = int) 
print(x)

[[0 9 0]
 [0 0 0]]


In [99]:
y = np.empty([1,4], dtype = int)
print(y)

[[0 0 0 0]]


In [100]:
# array of five ones. Default dtype is float
x = np.ones(5) 
print(x)

[1. 1. 1. 1. 1.]


### NumPy – Indexing & Slicing

In [117]:
a = np.arange(10) 
print(a)
print (a[slice(2,8)])
print(a[5])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7]
5


In [108]:
a = np.arange(10) 
b = a[2:7] 
print(b)

[2 3 4 5 6]


In [115]:
# slice single item 
a = np.arange(10) 
b = a[5] 
print(b)

5


In [111]:
# slice items starting from index
a = np.arange(10) 
print(a[2:])

[2 3 4 5 6 7 8 9]


In [ ]:
# slice items between indexes 
import numpy as np 
a = np.arange(10) 
print (a[2:5])

### NumPy – Advanced Indexing

In [113]:
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 
print ('Our array is:') 
print (x)
print ('\n')  

# Now we will print the items greater than 5 
print ('The items greater than 5 are:')
print (x[x > 5])


Our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


The items greater than 5 are:
[ 6  7  8  9 10 11]


### NumPy – Broadcasting

In [120]:
a = np.array([1,2,3,4]) 
b = np.array([5,20,30,40]) 
c = a * b 
print(c)

[  5  40  90 160]


### Array Iteration

In [121]:
arr1 = np.array([2, 1, 4])
for x in arr1:
    print(x)

2
1
4


In [127]:
arr = np.array([[[4, 3], [1, 4]], [[7, 6], [3, 2]]])
for x in arr:
    print(x)

[[4 3]
 [1 4]]
[[7 6]
 [3 2]]


In [122]:
# using nditer 
arr = np.array([[[4, 3], [1, 4]], [[7, 6], [3, 2]]])
for x in np.nditer(arr):
    print(x)

4
3
1
4
7
6
3
2


In [132]:
arr = np.array([[[4, 3], [1, 4]], [[7, 6], [3, 2]]])
for x in np.nditer(arr):
    print(x)

4
3
1
4
7
6
3
2


In [138]:
arr =  np.array([[8, 16, 44, 14, 77],[22, 30, 41, 44, 16]])
print(arr)
print(" ")
print(arr[:, ::2])
for x in np.nditer(arr[:, ::2]):
    print(x)

[[ 8 16 44 14 77]
 [22 30 41 44 16]]
 
[[ 8 44 77]
 [22 41 16]]
8
44
77
22
41
16


### NumPy – Statistical Functions

NumPy has quite a few useful statistical functions for finding minimum, maximum, percentile standard deviation and variance, etc. from the given elements in the array. The functions are explained as follows −

numpy.amin() and numpy.amax()numpy.amin() and numpy.amax()

These functions return the minimum and the maximum from the elements in the given array along the specified axis.

In [140]:
a = np.array([[3,7,5],[8,4,3],[2,4,9]]) 
print('Our array is:') 
print(a)  
print('\n')  
print('Applying amin() function:') 
print(np.amin(a)) 
print('\n')  
print('Applying amin() function again:') 
print(np.amin(a,0)) 
print('\n')  
print('Applying amax() function:') 
print(np.amax(a)) 
print('\n')
print('Applying amax() function again:') 
print(np.amax(a, axis = 0))

Our array is:
[[3 7 5]
 [8 4 3]
 [2 4 9]]


Applying amin() function:
2


Applying amin() function again:
[2 4 3]


Applying amax() function:
9


Applying amax() function again:
[8 7 9]


### Matrix Arithmetics under NumPy

In [141]:
x = np.array([1, 5, 2])
y = np.array([7, 4, 1])
x + y

array([8, 9, 3])

In [142]:
x-y

array([-6,  1,  1])

In [143]:
x/y

array([0.14285714, 1.25      , 2.        ])

In [144]:
x%y

array([1, 1, 0])

In [147]:
# dot or scalar product
x = np.array([1, 2, 3])
y = np.array([-7, 8, 9])
np.dot(x, y)

36

In [148]:
# matrix product
x = np.array( ((2,3), (3, 5)) )
y = np.matrix( ((1,2), (5, -1)) )
print(np.dot(x,y))

[[17  1]
 [28  1]]


### NumPy Searching Function

***np.argmax()***
This function returns the index of the maximum value in the array list. The search can be specific to a particular axis or the entire array.

In [149]:
import numpy as np
arr=np.array([[74,23],[56,98]])
print(np.argmax(arr))

3


***np.nanargmax()***
This function returns the index of the maximum value element after ignoring ‘Not a Number’ (NaN) values present in the list.

In [150]:
import numpy as np
arr=np.array([[74,np.nan,59],[56,98,np.nan]])
print(np.nanargmax(arr))

4


***np.argmin()***
This function returns the index of the minimum value in the array list. The search can be specific to a particular axis or the entire array.

In [151]:
import numpy as np
arr=np.array([[74,59],[56,98]])
print(np.argmin(arr))

2


***np.nanargmin()***
This function returns the index of the minimum value element after ignoring ‘Not a Number’ (NaN) values present in the list.

In [152]:
import numpy as np
arr=np.array([[74,np.nan,59],[56,98,np.nan]])
print(np.nanargmin(arr))

3


***np.extract()***
This function returns the array values that satisfy a particular condition

In [153]:
import numpy as np
arr=np.array([[74,33],[59,98]])
a=np.mod(arr,2) ==0
print(np.extract(a,arr))

[74 98]


***np.nonzero()***
This function search returns values that are non-zero.

In [154]:
arr=np.array([0,56,89,0,23])
print(np.nonzero(arr))

(array([1, 2, 4]),)


### NumPy Sorting Function

***np.sort()***
This function returns an array in sorted format.

In [156]:
arr = np.array([[16,1,47,53,87,28]])
print(np.sort(arr))

[[ 1 16 28 47 53 87]]


***np.argsort()***
This function returns the indices of the sorted array. We can perform this along a particular axis.

In [157]:
arr = np.array([[16,1,47,53,87,28]])
print(np.argsort(arr))

[[1 0 5 2 3 4]]


***np.lexsort()***
This function returns the indices of array elements indirectly sorted by using a key sequence.We can consider the last key as the primary one.

In [158]:
arr1 =np.array([[16,1,47,53,87,28]])
arr2 =np.array([[56,90,44,32,77,45]])
#sort by arr1 and then arr2
print(np.lexsort((arr2,arr1)))

[[1 0 5 2 3 4]]


### Numpy MCQs

### 1. Observe the following code and identify what will be the outcome?

import numpy as np 

x = np.array([[0, 1],
       [2, 3]])
       
np.transpose(x)

A. array([[0, 2],
       [1, 3]])
       
B. array([[0, 1],
       [2, 3]])
       
C. array([[2, 3],
       [0, 1]])
       
D. None of the mentioned above

In [159]:
import numpy as np 

x = np.array([[0, 1],
       [2, 3]])
       
np.transpose(x)

array([[0, 2],
       [1, 3]])

### 2. What will be printed? 

 import numpy as np
 
 a = np.array([1,2,3,5,8])
 
 b = np.array([0,3,4,2,1])
 
 c = a + b
 
 c = c*a
 
 print (c[2])
 
A. 7

B. 12

C. 10

D. 21

### 3. What will be output for the following code? 

 import numpy as np
 
 ary = np.array([1,2,3,5,8])
 
 ary = ary + 1
 
 print (ary[1])
 

 A. 0
 
 B. 1
 
 C. 2
 
 D. 3

### 4.  NumPy is often used along with packages like?

 A. Node.js
 
 B. Matplotlib
 
 C. SciPy
 
 D. Both B and C

### 5. How to convert numpy array to list?

 A. array.list()
 
 B. array.list
 
 C. list.array()
 
 D. list(array)

### 6. What is zero() function in numpy use to?

 A. make a matrix with first column 0
    
 B. make a matrix with all elements 0

 C. make a matrix with diagonal elements 0
    
 D. All of the above

## <u>Pandas</u>

Pandas is a Python library used for working with data sets.

It has functions for analyzing, cleaning, exploring, and manipulating data.

The name "Pandas" has a reference to both "Panel Data", and "Python Data Analysis" and was created by Wes McKinney in 2008.

Pandas allows us to analyze big data and make conclusions based on statistical theories.

Pandas can clean messy data sets, and make them readable and relevant.

Relevant data is very important in data science.

In [ ]:
import pandas as pd

In [210]:
df = pd.read_csv('BB.csv')
df

index                                            product  \
0      1             Garlic Oil - Vegetarian Capsule 500 mg   
1      2                              Water Bottle - Orange   
2      3                     Brass Angle Deep - Plain, No.2   
3      4  Cereal Flip Lid Container/Storage Jar - Assort...   
4      5                 Creme Soft Soap - For Hands & Body   
5      6                  Germ - Removal Multipurpose Wipes   
6      7                                       Multani Mati   
7      8                  Hand Sanitizer - 70% Alcohol Base   
8      9  Biotin & Collagen Volumizing Hair Shampoo + Bi...   
9     10               Scrub Pad - Anti- Bacterial, Regular   

                 category            sub_category              brand  \
0        Beauty & Hygiene               Hair Care  Sri Sri Ayurveda    
1  Kitchen, Garden & Pets   Storage & Accessories         Mastercook   
2    Cleaning & Household             Pooja Needs                Trm   
3    Cleaning & Household    Bins & Bathroom Ware             Nakoda   
4        Beauty & Hygiene        Bath & Hand Wash              Nivea   
5    Cleaning & Household    All Purpose Cleaners     Nature Protect   
6        Beauty & Hygiene               Skin Care          Satinance   
7        Beauty & Hygiene        Bath & Hand Wash            Bionova   
8        Beauty & Hygiene               Hair Care         StBotanica   
9    Cleaning & Household  Mops, Brushes & Scrubs       Scotch brite   

   sale_price  market_price                           type  rating  \
0         220           220               Hair Oil & Serum     4.1   
1         180           180         Water & Fridge Bottles     2.3   
2         119           250                Lamp & Lamp Oil     3.4   
3         149           176       Laundry, Storage Baskets     3.7   
4         162           162           Bathing Bars & Soaps     4.4   
5         169           199  Disinfectant Spray & Cleaners     3.3   
6          58            58                      Face Care     3.6   
7         250           250         Hand Wash & Sanitizers     4.0   
8        1098          1098          Shampoo & Conditioner     3.5   
9          20            20       Utensil Scrub-Pad, Glove     4.3   

                                         description  
0  This Product contains Garlic Oil that is known...  
1  Each product is microwave safe (without lid), ...  
2  A perfect gift for all occasions, be it your m...  
3  Multipurpose container with an attractive desi...  
4  Nivea Creme Soft Soap gives your skin the best...  
5  Stay protected from contamination with Multipu...  
6  Satinance multani matti is an excellent skin t...  
7  70%Alcohol based is gentle of hand leaves skin...  
8  An exclusive blend with Vitamin B7 Biotin, Hyd...  
9  Scotch Brite Anti- Bacterial Scrub Pad thoroug...

In [164]:
df.tail()

index                                            product  \
5      6                  Germ - Removal Multipurpose Wipes   
6      7                                       Multani Mati   
7      8                  Hand Sanitizer - 70% Alcohol Base   
8      9  Biotin & Collagen Volumizing Hair Shampoo + Bi...   
9     10               Scrub Pad - Anti- Bacterial, Regular   

               category            sub_category           brand  sale_price  \
5  Cleaning & Household    All Purpose Cleaners  Nature Protect         169   
6      Beauty & Hygiene               Skin Care       Satinance          58   
7      Beauty & Hygiene        Bath & Hand Wash         Bionova         250   
8      Beauty & Hygiene               Hair Care      StBotanica        1098   
9  Cleaning & Household  Mops, Brushes & Scrubs    Scotch brite          20   

   market_price                           type  rating  \
5           199  Disinfectant Spray & Cleaners     3.3   
6            58                      Face Care     3.6   
7           250         Hand Wash & Sanitizers     4.0   
8          1098          Shampoo & Conditioner     3.5   
9            20       Utensil Scrub-Pad, Glove     4.3   

                                         description  
5  Stay protected from contamination with Multipu...  
6  Satinance multani matti is an excellent skin t...  
7  70%Alcohol based is gentle of hand leaves skin...  
8  An exclusive blend with Vitamin B7 Biotin, Hyd...  
9  Scotch Brite Anti- Bacterial Scrub Pad thoroug...

In [211]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   index         10 non-null     int64  
 1   product       10 non-null     object 
 2   category      10 non-null     object 
 3   sub_category  10 non-null     object 
 4   brand         10 non-null     object 
 5   sale_price    10 non-null     int64  
 6   market_price  10 non-null     int64  
 7   type          10 non-null     object 
 8   rating        10 non-null     float64
 9   description   10 non-null     object 
dtypes: float64(1), int64(3), object(6)
memory usage: 928.0+ bytes


In [166]:
df.shape

(10, 10)

In [170]:
df.describe()

index   sale_price  market_price     rating
count  10.00000    10.000000     10.000000  10.000000
mean    5.50000   242.500000    261.300000   3.660000
std     3.02765   308.359909    303.536946   0.609554
min     1.00000    20.000000     20.000000   2.300000
25%     3.25000   126.500000    165.500000   3.425000
50%     5.50000   165.500000    189.500000   3.650000
75%     7.75000   210.000000    242.500000   4.075000
max    10.00000  1098.000000   1098.000000   4.400000

In [173]:
sum(df['sale_price'])

2425

### 👉 Slicing

In [176]:
# Row slicing
df[1:4]

index                                            product  \
1      2                              Water Bottle - Orange   
2      3                     Brass Angle Deep - Plain, No.2   
3      4  Cereal Flip Lid Container/Storage Jar - Assort...   

                 category           sub_category       brand  sale_price  \
1  Kitchen, Garden & Pets  Storage & Accessories  Mastercook         180   
2    Cleaning & Household            Pooja Needs         Trm         119   
3    Cleaning & Household   Bins & Bathroom Ware      Nakoda         149   

   market_price                      type  rating  \
1           180    Water & Fridge Bottles     2.3   
2           250           Lamp & Lamp Oil     3.4   
3           176  Laundry, Storage Baskets     3.7   

                                         description  
1  Each product is microwave safe (without lid), ...  
2  A perfect gift for all occasions, be it your m...  
3  Multipurpose container with an attractive desi...

In [178]:
# Indexing columns
df[['product', 'brand']][1:4]

product       brand
1                              Water Bottle - Orange  Mastercook
2                     Brass Angle Deep - Plain, No.2         Trm
3  Cereal Flip Lid Container/Storage Jar - Assort...      Nakoda

In [ ]:
# combining row and column slicing
df[['product', 'category']][1:4]

### 👉 Filtering

In [180]:
# get the products whose rating is 4 or more
df[df['rating']>=4][['product']]

product
0  Garlic Oil - Vegetarian Capsule 500 mg
4      Creme Soft Soap - For Hands & Body
7       Hand Sanitizer - 70% Alcohol Base
9    Scrub Pad - Anti- Bacterial, Regular

In [183]:
# combining multiple filter conditions
# get the products of beauty and hygine category with rating more than 4

df[ (df['category']=='Beauty & Hygiene') & (df['rating']>4) ]




index                                 product          category  \
0      1  Garlic Oil - Vegetarian Capsule 500 mg  Beauty & Hygiene   
4      5      Creme Soft Soap - For Hands & Body  Beauty & Hygiene   

       sub_category              brand  sale_price  market_price  \
0         Hair Care  Sri Sri Ayurveda          220           220   
4  Bath & Hand Wash              Nivea         162           162   

                   type  rating  \
0      Hair Oil & Serum     4.1   
4  Bathing Bars & Soaps     4.4   

                                         description  
0  This Product contains Garlic Oil that is known...  
4  Nivea Creme Soft Soap gives your skin the best...

### 👉 loc and iloc

In [185]:
df

index                                            product  \
0      1             Garlic Oil - Vegetarian Capsule 500 mg   
1      2                              Water Bottle - Orange   
2      3                     Brass Angle Deep - Plain, No.2   
3      4  Cereal Flip Lid Container/Storage Jar - Assort...   
4      5                 Creme Soft Soap - For Hands & Body   
5      6                  Germ - Removal Multipurpose Wipes   
6      7                                       Multani Mati   
7      8                  Hand Sanitizer - 70% Alcohol Base   
8      9  Biotin & Collagen Volumizing Hair Shampoo + Bi...   
9     10               Scrub Pad - Anti- Bacterial, Regular   

                 category            sub_category              brand  \
0        Beauty & Hygiene               Hair Care  Sri Sri Ayurveda    
1  Kitchen, Garden & Pets   Storage & Accessories         Mastercook   
2    Cleaning & Household             Pooja Needs                Trm   
3    Cleaning & Household    Bins & Bathroom Ware             Nakoda   
4        Beauty & Hygiene        Bath & Hand Wash              Nivea   
5    Cleaning & Household    All Purpose Cleaners     Nature Protect   
6        Beauty & Hygiene               Skin Care          Satinance   
7        Beauty & Hygiene        Bath & Hand Wash            Bionova   
8        Beauty & Hygiene               Hair Care         StBotanica   
9    Cleaning & Household  Mops, Brushes & Scrubs       Scotch brite   

   sale_price  market_price                           type  rating  \
0         220           220               Hair Oil & Serum     4.1   
1         180           180         Water & Fridge Bottles     2.3   
2         119           250                Lamp & Lamp Oil     3.4   
3         149           176       Laundry, Storage Baskets     3.7   
4         162           162           Bathing Bars & Soaps     4.4   
5         169           199  Disinfectant Spray & Cleaners     3.3   
6          58            58                      Face Care     3.6   
7         250           250         Hand Wash & Sanitizers     4.0   
8        1098          1098          Shampoo & Conditioner     3.5   
9          20            20       Utensil Scrub-Pad, Glove     4.3   

                                         description  
0  This Product contains Garlic Oil that is known...  
1  Each product is microwave safe (without lid), ...  
2  A perfect gift for all occasions, be it your m...  
3  Multipurpose container with an attractive desi...  
4  Nivea Creme Soft Soap gives your skin the best...  
5  Stay protected from contamination with Multipu...  
6  Satinance multani matti is an excellent skin t...  
7  70%Alcohol based is gentle of hand leaves skin...  
8  An exclusive blend with Vitamin B7 Biotin, Hyd...  
9  Scotch Brite Anti- Bacterial Scrub Pad thoroug...

In [184]:
# indexing
df.loc[1, 'product']

'Water Bottle - Orange'

In [186]:
# extracting dataframe
df.loc[[1], ['product']]

product
1  Water Bottle - Orange

In [187]:
# slicing
df.loc[1:5, 'product': 'type']

product                category  \
1                              Water Bottle - Orange  Kitchen, Garden & Pets   
2                     Brass Angle Deep - Plain, No.2    Cleaning & Household   
3  Cereal Flip Lid Container/Storage Jar - Assort...    Cleaning & Household   
4                 Creme Soft Soap - For Hands & Body        Beauty & Hygiene   
5                  Germ - Removal Multipurpose Wipes    Cleaning & Household   

            sub_category           brand  sale_price  market_price  \
1  Storage & Accessories      Mastercook         180           180   
2            Pooja Needs             Trm         119           250   
3   Bins & Bathroom Ware          Nakoda         149           176   
4       Bath & Hand Wash           Nivea         162           162   
5   All Purpose Cleaners  Nature Protect         169           199   

                            type  
1         Water & Fridge Bottles  
2                Lamp & Lamp Oil  
3       Laundry, Storage Baskets  
4           Bathing Bars & Soaps  
5  Disinfectant Spray & Cleaners

In [189]:
# indexing rows and slicing columns
df.loc[[3,6], 'category':'sale_price']

category          sub_category      brand  sale_price
3  Cleaning & Household  Bins & Bathroom Ware     Nakoda         149
6      Beauty & Hygiene             Skin Care  Satinance          58

In [ ]:
# adding rows using loc
df.loc[11] = ['product', 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
df.loc[[11]]

In [ ]:
# deleting row
df.drop(11, axis=0, inplace=True)
df

In [191]:
df

index                                            product  \
0      1             Garlic Oil - Vegetarian Capsule 500 mg   
1      2                              Water Bottle - Orange   
2      3                     Brass Angle Deep - Plain, No.2   
3      4  Cereal Flip Lid Container/Storage Jar - Assort...   
4      5                 Creme Soft Soap - For Hands & Body   
5      6                  Germ - Removal Multipurpose Wipes   
6      7                                       Multani Mati   
7      8                  Hand Sanitizer - 70% Alcohol Base   
8      9  Biotin & Collagen Volumizing Hair Shampoo + Bi...   
9     10               Scrub Pad - Anti- Bacterial, Regular   

                 category            sub_category              brand  \
0        Beauty & Hygiene               Hair Care  Sri Sri Ayurveda    
1  Kitchen, Garden & Pets   Storage & Accessories         Mastercook   
2    Cleaning & Household             Pooja Needs                Trm   
3    Cleaning & Household    Bins & Bathroom Ware             Nakoda   
4        Beauty & Hygiene        Bath & Hand Wash              Nivea   
5    Cleaning & Household    All Purpose Cleaners     Nature Protect   
6        Beauty & Hygiene               Skin Care          Satinance   
7        Beauty & Hygiene        Bath & Hand Wash            Bionova   
8        Beauty & Hygiene               Hair Care         StBotanica   
9    Cleaning & Household  Mops, Brushes & Scrubs       Scotch brite   

   sale_price  market_price                           type  rating  \
0         220           220               Hair Oil & Serum     4.1   
1         180           180         Water & Fridge Bottles     2.3   
2         119           250                Lamp & Lamp Oil     3.4   
3         149           176       Laundry, Storage Baskets     3.7   
4         162           162           Bathing Bars & Soaps     4.4   
5         169           199  Disinfectant Spray & Cleaners     3.3   
6          58            58                      Face Care     3.6   
7         250           250         Hand Wash & Sanitizers     4.0   
8        1098          1098          Shampoo & Conditioner     3.5   
9          20            20       Utensil Scrub-Pad, Glove     4.3   

                                         description  
0  This Product contains Garlic Oil that is known...  
1  Each product is microwave safe (without lid), ...  
2  A perfect gift for all occasions, be it your m...  
3  Multipurpose container with an attractive desi...  
4  Nivea Creme Soft Soap gives your skin the best...  
5  Stay protected from contamination with Multipu...  
6  Satinance multani matti is an excellent skin t...  
7  70%Alcohol based is gentle of hand leaves skin...  
8  An exclusive blend with Vitamin B7 Biotin, Hyd...  
9  Scotch Brite Anti- Bacterial Scrub Pad thoroug...

In [193]:
# filtering using iloc

# optaining specific positioned values
df.iloc[2,3]

'Pooja Needs'

In [194]:
# slicing
df.iloc[0:5, 0:3]

index                                            product  \
0      1             Garlic Oil - Vegetarian Capsule 500 mg   
1      2                              Water Bottle - Orange   
2      3                     Brass Angle Deep - Plain, No.2   
3      4  Cereal Flip Lid Container/Storage Jar - Assort...   
4      5                 Creme Soft Soap - For Hands & Body   

                 category  
0        Beauty & Hygiene  
1  Kitchen, Garden & Pets  
2    Cleaning & Household  
3    Cleaning & Household  
4        Beauty & Hygiene

In [195]:
# indexing and slicing
df.iloc[[0,2,5], 0:3]

index                                 product              category
0      1  Garlic Oil - Vegetarian Capsule 500 mg      Beauty & Hygiene
2      3          Brass Angle Deep - Plain, No.2  Cleaning & Household
5      6       Germ - Removal Multipurpose Wipes  Cleaning & Household

### 👉 Sorting Values

In [196]:
# sorting numerical column
df.sort_values(by='sale_price')

index                                            product  \
9     10               Scrub Pad - Anti- Bacterial, Regular   
6      7                                       Multani Mati   
2      3                     Brass Angle Deep - Plain, No.2   
3      4  Cereal Flip Lid Container/Storage Jar - Assort...   
4      5                 Creme Soft Soap - For Hands & Body   
5      6                  Germ - Removal Multipurpose Wipes   
1      2                              Water Bottle - Orange   
0      1             Garlic Oil - Vegetarian Capsule 500 mg   
7      8                  Hand Sanitizer - 70% Alcohol Base   
8      9  Biotin & Collagen Volumizing Hair Shampoo + Bi...   

                 category            sub_category              brand  \
9    Cleaning & Household  Mops, Brushes & Scrubs       Scotch brite   
6        Beauty & Hygiene               Skin Care          Satinance   
2    Cleaning & Household             Pooja Needs                Trm   
3    Cleaning & Household    Bins & Bathroom Ware             Nakoda   
4        Beauty & Hygiene        Bath & Hand Wash              Nivea   
5    Cleaning & Household    All Purpose Cleaners     Nature Protect   
1  Kitchen, Garden & Pets   Storage & Accessories         Mastercook   
0        Beauty & Hygiene               Hair Care  Sri Sri Ayurveda    
7        Beauty & Hygiene        Bath & Hand Wash            Bionova   
8        Beauty & Hygiene               Hair Care         StBotanica   

   sale_price  market_price                           type  rating  \
9          20            20       Utensil Scrub-Pad, Glove     4.3   
6          58            58                      Face Care     3.6   
2         119           250                Lamp & Lamp Oil     3.4   
3         149           176       Laundry, Storage Baskets     3.7   
4         162           162           Bathing Bars & Soaps     4.4   
5         169           199  Disinfectant Spray & Cleaners     3.3   
1         180           180         Water & Fridge Bottles     2.3   
0         220           220               Hair Oil & Serum     4.1   
7         250           250         Hand Wash & Sanitizers     4.0   
8        1098          1098          Shampoo & Conditioner     3.5   

                                         description  
9  Scotch Brite Anti- Bacterial Scrub Pad thoroug...  
6  Satinance multani matti is an excellent skin t...  
2  A perfect gift for all occasions, be it your m...  
3  Multipurpose container with an attractive desi...  
4  Nivea Creme Soft Soap gives your skin the best...  
5  Stay protected from contamination with Multipu...  
1  Each product is microwave safe (without lid), ...  
0  This Product contains Garlic Oil that is known...  
7  70%Alcohol based is gentle of hand leaves skin...  
8  An exclusive blend with Vitamin B7 Biotin, Hyd...

In [197]:
# sorting in descending order
df.sort_values(by='sale_price', ascending=False)

index                                            product  \
8      9  Biotin & Collagen Volumizing Hair Shampoo + Bi...   
7      8                  Hand Sanitizer - 70% Alcohol Base   
0      1             Garlic Oil - Vegetarian Capsule 500 mg   
1      2                              Water Bottle - Orange   
5      6                  Germ - Removal Multipurpose Wipes   
4      5                 Creme Soft Soap - For Hands & Body   
3      4  Cereal Flip Lid Container/Storage Jar - Assort...   
2      3                     Brass Angle Deep - Plain, No.2   
6      7                                       Multani Mati   
9     10               Scrub Pad - Anti- Bacterial, Regular   

                 category            sub_category              brand  \
8        Beauty & Hygiene               Hair Care         StBotanica   
7        Beauty & Hygiene        Bath & Hand Wash            Bionova   
0        Beauty & Hygiene               Hair Care  Sri Sri Ayurveda    
1  Kitchen, Garden & Pets   Storage & Accessories         Mastercook   
5    Cleaning & Household    All Purpose Cleaners     Nature Protect   
4        Beauty & Hygiene        Bath & Hand Wash              Nivea   
3    Cleaning & Household    Bins & Bathroom Ware             Nakoda   
2    Cleaning & Household             Pooja Needs                Trm   
6        Beauty & Hygiene               Skin Care          Satinance   
9    Cleaning & Household  Mops, Brushes & Scrubs       Scotch brite   

   sale_price  market_price                           type  rating  \
8        1098          1098          Shampoo & Conditioner     3.5   
7         250           250         Hand Wash & Sanitizers     4.0   
0         220           220               Hair Oil & Serum     4.1   
1         180           180         Water & Fridge Bottles     2.3   
5         169           199  Disinfectant Spray & Cleaners     3.3   
4         162           162           Bathing Bars & Soaps     4.4   
3         149           176       Laundry, Storage Baskets     3.7   
2         119           250                Lamp & Lamp Oil     3.4   
6          58            58                      Face Care     3.6   
9          20            20       Utensil Scrub-Pad, Glove     4.3   

                                         description  
8  An exclusive blend with Vitamin B7 Biotin, Hyd...  
7  70%Alcohol based is gentle of hand leaves skin...  
0  This Product contains Garlic Oil that is known...  
1  Each product is microwave safe (without lid), ...  
5  Stay protected from contamination with Multipu...  
4  Nivea Creme Soft Soap gives your skin the best...  
3  Multipurpose container with an attractive desi...  
2  A perfect gift for all occasions, be it your m...  
6  Satinance multani matti is an excellent skin t...  
9  Scotch Brite Anti- Bacterial Scrub Pad thoroug...

### 👉 Missing Values

In [198]:
import numpy as np

In [199]:
dict = {'First Score':[100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score':[np.nan, 40, 80, 98]}
 
# creating a dataframe from list
df = pd.DataFrame(dict)
df

First Score  Second Score  Third Score
0        100.0          30.0          NaN
1         90.0          45.0         40.0
2          NaN          56.0         80.0
3         95.0           NaN         98.0

In [200]:
# using isnull() function 
df.isnull()

First Score  Second Score  Third Score
0        False         False         True
1        False         False        False
2         True         False        False
3        False          True        False

In [201]:
# using notnull() function 
df.notnull()

First Score  Second Score  Third Score
0         True          True        False
1         True          True         True
2        False          True         True
3         True         False         True

In [203]:
# filling missing value using fillna() 
df.fillna(99)

First Score  Second Score  Third Score
0        100.0          30.0         99.0
1         90.0          45.0         40.0
2         99.0          56.0         80.0
3         95.0          99.0         98.0

In [204]:
# filling a missing value with the previous ones 
df.fillna(method ='pad')

First Score  Second Score  Third Score
0        100.0          30.0          NaN
1         90.0          45.0         40.0
2         90.0          56.0         80.0
3         95.0          56.0         98.0

In [205]:
# filling null value using fillna() function 
df.fillna(method ='bfill')

First Score  Second Score  Third Score
0        100.0          30.0         40.0
1         90.0          45.0         40.0
2         95.0          56.0         80.0
3         95.0           NaN         98.0

In [206]:
# will replace  Nan value in dataframe with value 999 
df.replace(to_replace = np.nan, value = 999)

First Score  Second Score  Third Score
0        100.0          30.0        999.0
1         90.0          45.0         40.0
2        999.0          56.0         80.0
3         95.0         999.0         98.0

In [207]:
# using dropna() function 
df.dropna()

First Score  Second Score  Third Score
1         90.0          45.0         40.0

In [208]:
# using dropna() function to delete rows with all nans 
df.dropna(how = 'all')

First Score  Second Score  Third Score
0        100.0          30.0          NaN
1         90.0          45.0         40.0
2          NaN          56.0         80.0
3         95.0           NaN         98.0

In [209]:
# using dropna() function to delete columns with atleast 1 missing value  
df.dropna(axis = 1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

### Typecasting a series of the dataframe - astype(),to_numeric()

In [212]:
df['rating'].dtype

dtype('float64')

In [221]:
df['rating'] = df['rating'].astype('float16')
df['rating'].dtype

dtype('float16')

In [216]:
ser = pd.Series(df['rating'])
ser

0    4.101562
1    2.300781
2    3.400391
3    3.699219
4    4.398438
5    3.300781
6    3.599609
7    4.000000
8    3.500000
9    4.300781
Name: rating, dtype: float64

In [219]:
ser = pd.to_numeric(ser, downcast ='float')

In [220]:
pd.to_numeric(ser, downcast ='float')

0    4.101562
1    2.300781
2    3.400391
3    3.699219
4    4.398438
5    3.300781
6    3.599609
7    4.000000
8    3.500000
9    4.300781
Name: rating, dtype: float32

### Comparing pandas series

In [ ]:
ps1 = pd.Series([2.5, 4, 6, 8, 10, 1.75, 40])
ps2 = pd.Series([1.5, 3, 5, 7, 10, 1.75, 20])
  
print("Series1:")
print(ps1)
print("\nSeries2:")
print(ps2)
  
# Comparing two series using Series.equals()
# function
print("\nResult of comparing Two Series:")
result = ps1.equals(other=ps2)
print(result)

### nlargest and nsmallest

In [225]:
df.nlargest(2, columns='sale_price')

index                                            product          category  \
8      9  Biotin & Collagen Volumizing Hair Shampoo + Bi...  Beauty & Hygiene   
7      8                  Hand Sanitizer - 70% Alcohol Base  Beauty & Hygiene   

       sub_category       brand  sale_price  market_price  \
8         Hair Care  StBotanica        1098          1098   
7  Bath & Hand Wash     Bionova         250           250   

                     type  rating  \
8   Shampoo & Conditioner     3.5   
7  Hand Wash & Sanitizers     4.0   

                                         description  
8  An exclusive blend with Vitamin B7 Biotin, Hyd...  
7  70%Alcohol based is gentle of hand leaves skin...

In [227]:
df.nsmallest(7, columns='sale_price')

index                                            product  \
9     10               Scrub Pad - Anti- Bacterial, Regular   
6      7                                       Multani Mati   
2      3                     Brass Angle Deep - Plain, No.2   
3      4  Cereal Flip Lid Container/Storage Jar - Assort...   
4      5                 Creme Soft Soap - For Hands & Body   
5      6                  Germ - Removal Multipurpose Wipes   
1      2                              Water Bottle - Orange   

                 category            sub_category           brand  sale_price  \
9    Cleaning & Household  Mops, Brushes & Scrubs    Scotch brite          20   
6        Beauty & Hygiene               Skin Care       Satinance          58   
2    Cleaning & Household             Pooja Needs             Trm         119   
3    Cleaning & Household    Bins & Bathroom Ware          Nakoda         149   
4        Beauty & Hygiene        Bath & Hand Wash           Nivea         162   
5    Cleaning & Household    All Purpose Cleaners  Nature Protect         169   
1  Kitchen, Garden & Pets   Storage & Accessories      Mastercook         180   

   market_price                           type    rating  \
9            20       Utensil Scrub-Pad, Glove  4.300781   
6            58                      Face Care  3.599609   
2           250                Lamp & Lamp Oil  3.400391   
3           176       Laundry, Storage Baskets  3.699219   
4           162           Bathing Bars & Soaps  4.398438   
5           199  Disinfectant Spray & Cleaners  3.300781   
1           180         Water & Fridge Bottles  2.300781   

                                         description  
9  Scotch Brite Anti- Bacterial Scrub Pad thoroug...  
6  Satinance multani matti is an excellent skin t...  
2  A perfect gift for all occasions, be it your m...  
3  Multipurpose container with an attractive desi...  
4  Nivea Creme Soft Soap gives your skin the best...  
5  Stay protected from contamination with Multipu...  
1  Each product is microwave safe (without lid), ...

### References: 
https://www.mygreatlearning.com/blog/python-numpy-tutorial/

https://python-course.eu/numerical-programming/matrix-arithmetics-under-numpy-and-python.php

https://data-flair.training/blogs/numpy-search-sort-and-count/